#!/usr/bin/env python
# -*- coding: utf-8 -*-

from iamrocketman import play
import time

# list_song = params.song.split(sep='&')
play.play_song()
# for verse in list_song:
#     print(verse)
#     time.sleep(2)
